apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-exporter
  name: kafka-exporter
spec:
  ports:
    - name: "9308"
      port: 9308
      targetPort: 9308
  selector:
    io.kompose.service: kafka-exporter
status:
  loadBalancer: {}
