name: GitHub Actions
run-name: Main GitHub Actions
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0


      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Extract branch name
        id: vars
        shell: bash
        run: echo "::set-output name=dt::$(echo `date +%s`)"

      - name: Build and Push the Docker image
        run: |
          docker build . -t ${{secrets.DOCKER_NAME}}/${{secrets.DOCKER_REPO}}:${{steps.vars.outputs.dt}}
          docker login -u${{secrets.DOCKER_ID}} -p${{secrets.DOCKER_PW}}
          docker push ${{secrets.DOCKER_NAME}}/${{secrets.DOCKER_REPO}}:${{steps.vars.outputs.dt}}

      - name: Update kubernetes manifest
        run: |          
          git pull 
          sed -i 's/image:.*/image: ${{secrets.DOCKER_NAME}}\/${{secrets.DOCKER_REPO}}:${{steps.vars.outputs.dt}}/g' kube/spring-boot-application-deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email ${{secrets.EMAIL}}
          git add -A
          git commit -m 'update manifest'
          git push
